services:
  app:
    build:
      context: .
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 150M
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/app
    